#!/bin/sh
# configversion: 35e58d904c9b845fd8e8e2e99d555a8f

# shellcheck source=scripts/core/sxmo_common.sh
. sxmo_common.sh

# Please modify this file to your liking

# Important Instructions:
#  All processes you launch from this script must
#  be non-blocking: launch them in the background (using &)
#  or ensure they return quickly. Only after this script
#  finishes will the window manager be loaded

# You will sometime get SMS or calls from not
#  country code prefixed phone numbers. To make
#  it easy to fixup configure the default countryu.
#export DEFAULT_COUNTRY=FR

### Configuration Parameters ###

# Note that this is just a subset of all available
# parameters, see the sxmo documentation for more.

# Use firefox as default browser if installed
command -v firefox >/dev/null && export BROWSER=firefox

# Prepopulate Subreddits menu with custom subreddits
#export SXMO_SUBREDDITS="postmarketos pinephoneOfficial pinephone unixporn"

# Change the default terminal command
# export TERMCMD="st -e"

# When scrolling past the beginning or end of a menu, wrap it around:
#export DMENU_WRAP_AROUND=1

# Enable audio feedback on keypress
#export KEYBOARD_ARGS="-o | clickclack -f $(xdg_data_path sxmo/keytap.wav)"

# Or, enable vibration feedback on keypress
#export KEYBOARD_ARGS="-o | clickclack -V"

# Set the scale factor in sway
# export SXMO_SWAY_SCALE=2

export BEMENU_OPTS="--fn 'GoMono Nerd Font:size=12'\
 --scrollbar autohide\
 -s -n -w -c -l8 -M 40 -H 20\
 --cb '#1d1d1f'\
 --cf '#cfcfd2'\
 --tb '#7a002b'\
 --tf '#dedee0'\
 --fb '#1d1d1f'\
 --ff '#cfcfd2'\
 --nb '#1d1d1f'\
 --af '#cfcfd2'\
 --ab '#1d1d1f'\
 --nf '#cfcfd2'\
 --hb '#7a002b'\
 --hf '#dedee0'\
 --scb '#7a002b'\
 --scf '#dedee0'\
 --fbb '#dedee0'\
 --fbf '#1d1d1f'"

# To load specific part of configuration depending on the running environment
case "$SXMO_WM" in
	sway)
		;;
	dwm)
		;;
esac

#Set RINGTONE to audio file to play for incoming call
export SXMO_RINGTONE="$(xdg_data_path sxmo/ring.ogg)"

#Set TEXTSOUND to audio file to play when received text message
export SXMO_TEXTSOUND="$(xdg_data_path sxmo/notify.ogg)"

#Set RINGTIME to number of seconds the phone will ring
export SXMO_RINGTIME=20

#Set RINGNUMBER to number of times phone will ring or repeat ringtone
#(whichever of SXMO_RINGTIME or SXMO_RINGNUMBER runs less will limit how long phone rings)
export SXMO_RINGNUMER=10

#Set to the default text for a new text message.
export SXMO_DEFAULT_DRAFT="Enter new message here."
