#! /bin/sh

sxhkd &

#一 二 三 四 五 六 七 八 九 十
# ᚠ ᚢ ᚦ ᚨ ᚱ ᚲ ᚷ ᚹ ᚺ ᚾ ᛁ ᛃ ᛈ ᛇ ᛉ ᛊ ᛏ ᛒ ᛖ ᛗ ᛚ ᛜ ᛞ ᛟ
# ᚠ ᚢ ᚦ ᚬ ᚱ ᚴ ᚼ ᚾ ᛁ ᛅ ᛦ ᛋ ᛏ ᛒ ᛘ ᛚ


bspc monitor DP-2 -d ᚠ ᚢ ᚦ ᚨ ᚱ 
bspc monitor HDMI-0 -d ᚲ ᛉ ᛊ ᛏ ᛟ
bspc monitor DP-2 -s HDMI-0

polybar -r main &
polybar -r seconday &

xsetroot -cursor_name left_ptr

bspc config border_width         2
bspc config window_gap          12

bspc config active_border_color \#5f819d
bspc config normal_border_color \#85678f
bspc config focused_border_color \#8abeb7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus       true
bspc config pointer_modifier     mod1

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled

#nm-applet &

#pgrep bspswallow || bspswallow &
